[versions]
agp = "9.1.1"
android-compileSdk = "36"
android-minSdk = "24"
#noinspection OldTargetApi
android-targetSdk = "35"
androidx-activity = "1.13.0"
androidx-lifecycle = "2.11.0"
bignum = "0.3.10"
componentsResources = "1.11.1"
composeMultiplatform = "1.11.1"
coreKtx = "1.19.0"
foundation = "1.11.1"
haze = "1.7.2"
jetbrainsKotlinxSerializationJson = "1.11.0"
json = "20260719"
kotlin = "2.4.10"
kotlinx-coroutines = "1.11.0"
kotlinxDatetime = "0.8.0"
kotlinxSerializationJson = "1.11.0"
kotlinxSerializationJsonVersion = "1.11.0"
material3 = "1.9.0"
runtime = "1.11.1"
uiTooling = "1.11.1"
okio = "3.18.1"

[libraries]
#noinspection SimilarGradleDependency
androidx-core-ktx-v1120 = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
bignum = { module = "com.ionspin.kotlin:bignum", version.ref = "bignum" }
bignum-serialization-kotlinx = { module = "com.ionspin.kotlin:bignum-serialization-kotlinx", version.ref = "bignum" }
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "componentsResources" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "foundation" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
json = { module = "org.json:json", version.ref = "json" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
#noinspection SimilarGradleDependency
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
#noinspection SimilarGradleDependency
kotlinx-serialization-json-v180 = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "jetbrainsKotlinxSerializationJson" }
#noinspection SimilarGradleDependency
kotlinx-serialization-json-v190 = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJsonVersion" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "runtime" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "uiTooling" }
ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "uiTooling" }
#noinspection SimilarGradleDependency
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
#noinspection SimilarGradleDependency
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "uiTooling" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }